services:
  homeassistant:
    container_name: hacasa-ha-test
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: "no"
    ports:
      - "8123:8123"
    volumes:
      - ./.ha-test/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Europe/Lisbon
